services:
  app:
    image: linuxserver/jellyfin:latest
    volumes:
      - config_data:/config
      - media_data:/media
      - cache_data:/cache
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - JELLYFIN_PublishedServerUrl=https://jellyfin.henriqzimer.com.br
    networks:
      - traefik-proxy
      - cloudflared-proxy
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:8096/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
        monitor: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '4.0'
          memory: 3G
        reservations:
          cpus: '2.0'
          memory: 2G
      labels:
        - traefik.enable=true
        - traefik.http.routers.jellyfin.rule=Host(`jellyfin.henriqzimer.com.br`)
        - traefik.http.routers.jellyfin.entrypoints=websecure
        - traefik.http.routers.jellyfin.tls=true
        - traefik.http.routers.jellyfin.tls.certresolver=cloudflare
        - traefik.http.routers.jellyfin.middlewares=web-chain@file
        - traefik.http.services.jellyfin.loadbalancer.server.port=8096

volumes:
  config_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=altaria.henriqzimer.com.br,nfsvers=4,rw
      device: ':/mnt/altaria/docker/jellyfin/config'
  media_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=slowbro.henriqzimer.com.br,nfsvers=4,rw
      device: ':/mnt/slowbro/downloads'
  cache_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=altaria.henriqzimer.com.br,nfsvers=4,rw
      device: ':/mnt/altaria/docker/jellyfin/cache'

networks:
  cloudflared-proxy:
    external: true
    name: cloudflared_proxy-network
  traefik-proxy:
    external: true
    name: traefik_proxy-network
